### PR TITLE
Change for statement.

### PR DESCRIPTION
**Pull request by kitwtnb**
## Issue
- https://github.com/DroidKaigi/conference-app-2017/pull/366

## Overview (Required)
- Because create new instance every time.

## Links
- none

Thank for @eneim !
I learned a lot. 😇  
Is this OK?

### CODE REVIEW

**Comment by konifar** [comment]
👀 
@kitwtnb Awesome! Thanks for quick fix! LGTM
@eneim Can you review?

**Comment by jmatsu** [comment]
What do you mean by `every time`?

```
for (Some some: createSomeList()) {
  ...
}
```

is equal to

```
for (Iterator iterator = createSomeList().iterator(); iterator.hasNext();) {
  Some some = (Some) myIterator.next();
  ...
}
```

The number of instance creations is same with the current one.

**Comment by eneim** [comment]
@konifar @kitwtnb sorry for the late reply, my exp is exactly as the following article: [link to Medium](https://medium.com/google-developers/developing-for-android-ii-bb9a51f8c8b9#.3kq94vucn). It was from 2015, but still a good practice to reference. Please take a look at the whole. I will try some profiling in current code base though.

**Comment by konifar** [comment]
@eneim Does this PR look good for you? 🤔

**Comment by eneim** [comment]
Ah sorry, @konifar @kitwtnb this **looks good to me** for the onDraw :D. FYI there are few steps to improve this class if you are really crazy about the performance. But don't spend too much time, I just want to mention a general practice :D.

**Comment by konifar** [comment]
Thanks! 👍

**Pull request merged**
