### PR TITLE
Install DeployGate SDK

### PR DESCRIPTION
**Pull request by KeithYokoma**
- This enables us to collect crash logs in DeployGate console

### CODE REVIEW

**Comment by konifar** [comment]
Question 🙋 
I think FirebaseCrash is enough to collect crash logs 🤔 
Is there any other reason to introduce this sdk?

**Comment by KeithYokoma** [comment]
FirebaseCrash is for a production I think.
And if some crash happens, DeployGate immediately notify us via webhook so we can see the report in Slack 😃 .

**Comment by konifar** [comment]
Make sense. Okay. Let's try to taste it 🍸

**Comment by KeithYokoma** [comment]
I've heard that they will soon make some sweet update on the SDK to send a feedback within the app 🎉 . Let's see.

**Comment by jmatsu** [comment]
@KeithYokoma 
No need to add the dependency to only debug?

**Comment by KeithYokoma** [comment]
@jmatsu No concern for the dependency configuration because DeployGate can collect crash logs in a release build!

**Comment by jmatsu** [comment]
Sure! Let's take a taste of it. :wine_glass:

**Comment by hotchemi** [comment]
well, we have a crash report mechanism for debug build as well? I've gotten emails.

**Comment by konifar** [comment]
@hotchemi You mean the crash report for debug build may be noisy?

**Comment by hotchemi** [comment]
@konifar No no I mean we're already collecting crash reports for debug build.
@KeithYokoma Your aim is to integrating Slack and crash report?

**Comment by KeithYokoma** [comment]
@hotchemi Yeah that's my primary intention. In addition to this, we can collect logcat from DeployGate web console remotely in real time if we have permission, so that might help debugging as well.

**Pull request merged**
