### PR TITLE
Translate messages when check/uncheck the session

### PR DESCRIPTION
**Pull request by ogapants**
## Issue
- none

## Overview (Required)
- for Japanese 🇯🇵 

## Links
- none

## Screenshot
- none

### CODE REVIEW

**Comment by konifar** [comment]
LGTM!
BTW, `マイリストに追加する` may be better because there is my sessions page now.

**Comment by ogapants** [comment]
Like this?

- このセッションをマイリストに追加しました。
- このセッションをマイリストから削除しました。
- マイリストに追加
- マイリストから削除

And shall I change English messages too? 🤔 
- Checked this session -> Added this session to my list
- Unchecked this session -> Remove this session from my list
- Check -> Add
- Uncheck -> Remove

**Comment by konifar** [comment]
@ogapants Sorry to be late 🙇 Yes, right.
But I'm not sure... @ken5scal Can you help? 👰

**Comment by konifar** [comment]
@ogapants If the reply comment will not come by 12:00 JST, can you change the message as you commented 🙇  https://github.com/DroidKaigi/conference-app-2017/pull/371#issuecomment-281108602

**Comment by ogapants** [comment]
@konifar OK!
BTW, why do you ask him...?

**Comment by konifar** [comment]
He is good at English 😃

**Comment by ogapants** [comment]
Oh, I see 😆

**Comment by ogapants** [comment]
@konifar 
Sorry, I reconsidered about messages... 🤔 
Currently, in most other cases, the word "check" is used instead of "add".
So I think that it is good to remain "check". And as for Japanese, "チェックする" may be better.
What do you think about this?

**Comment by konifar** [comment]
Okay! Actually I don't have strong opinion about it and your suggestion makes sense for me.
Let me merge! Sorry for long review and thanks a lot!

**Comment by ogapants** [comment]
Thank you for review 🙇

**Pull request merged**
