### PR TITLE
Fix ripple effect in sponsor logo

### PR DESCRIPTION
**Pull request by shihochan**
## Issue
- none

## Overview (Required)
- I was going to add ripple effect in sponsor logo.

## Links
- none

## Screenshot

Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by KeithYokoma** [comment]
[LGTM](https://lgtm.in/i/Yucdkh6qq)

[:+1:](https://lgtm.in/u/Yucdkh6qq)

**Comment by konifar** [comment]
You are "friends" who is good at improving :tiger:
LGTM! Thanks! 💯

**Comment by jmatsu** [comment]
Marveloooooooooooous

**Comment by KeithYokoma** [comment]
Totally fun!!!

**Comment by shihochan** [comment]
yay! great! Fun! We are FRIENDS! 🐯

**Pull request merged**
