### PR TITLE
Change launcher icon

### PR DESCRIPTION
**Pull request by ShogoMizumoto**
## Issue

- #83

## Overview (Required)

- I made an icon with reference to @wariemon created icon. http://wariemon.com/post/151555749659/droidkaigi2017

## Links

- http://wariemon.com/post/151555749659/droidkaigi2017

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by u-nation** [comment]
How cute icon this is!

@ShogoMizumoto @konifar Shoud I send PR which has debug icon as below?? 🙇 

## Screenshot

ic_launcher

**Comment by konifar** [comment]
@ShogoMizumoto Thanks for tackling! LGTM 👍 Just in case, I'll ask to wariemon-san later 😉

**Comment by konifar** [comment]
@u-nation Good point. I'll merge this first. After that, can you send another PR? 😃

**Comment by konifar** [comment]
LGTM! 💯

**Pull request merged**
