### PR TITLE
add new sponsor

### PR DESCRIPTION
**Pull request by mhidaka**
## Overview (Required)
:tada: welcome new sponsor :tada:

## Links
- https://droidkaigi.github.io/2017/#sponsors

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Wow! Thanks @mhidaka and Pixiv Inc 👏

**Comment by konifar** [comment]
Brilliant 💃 LGTM!

**Comment by mhidaka** [comment]
thanks for your quick response!

**Pull request merged**
