### PR TITLE
add reload when comming back from session detail

### PR DESCRIPTION
**Pull request by kwmt**
## Issue
- #232 

## Overview (Required)
-  Search result scree  can  reload when coming back from session detail.

## Links
- https://github.com/DroidKaigi/conference-app-2017/pull/264

## Screenshot
Before | After
:--: | :--:
 | 

I notice session title is overlapping with speaker image.

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
LGTM!! 💯

**Comment by konifar** [comment]
Thanks for contribution!!

**Comment by kwmt** [comment]
Thank you for reviewing!

**Pull request merged**
