### PR TITLE
Change topic colors

### PR DESCRIPTION
**Pull request by takuaraki**
## Issue
- #234 

## Overview (Required)
How about Material Design Color A700?

## Links
- [Material Design Colors](https://material.io/guidelines/style/color.html#)

## Screenshot
- Light Green
- Amber
- Red
- Blue
- Light Blue
- Pink
- Purple

### CODE REVIEW

**Comment by konifar** [comment]
Thank you!
I think your suggested colors are too vivid 🤔 
Sorry for my obscure issue 🙇 

In my opinion, these colors should be extracted from web page.
https://droidkaigi.github.io/2017/

Can you change saturation of original topic colors in colors.xml? I usually use this page.
http://www.color-hex.com/color/58037c

**Comment by takuaraki** [comment]
Do you mean that I should use the url below when I improve `TopicColor.ARCHITECTURE_AND_DEVELOPMENT_PROCESS_METHODOLOGY` which using `#ffeb3b` for vivid color?:
http://www.color-hex.com/color/ffeb3b

**Comment by konifar** [comment]
Hmm, I'm not sure which colors are best.
So I'll ask to the designer in DroidKaigi members and decide new colors.
Can you wait? 🙇  I'll ping you after the colors will be decided.

**Comment by takuaraki** [comment]
OK. I'm looking forward to your ping!

By the way. May I close this PR because the commits do not suit your opinion?

**Comment by konifar** [comment]
> By the way. May I close this PR because the commits do not suit your opinion?

Yes, close this. Sorry 🙇 Anyway, thank you for your contribution!

**Pull request closed without merging**
