### PR TITLE
remove unused import statements

### PR DESCRIPTION
**Pull request by lvla**
## Issue
- none

## Overview (Required)
- remove unused import statements

### CODE REVIEW

**Comment by konifar** [comment]
Good catch! LGTM! 👍

**Comment by konifar** [comment]
CI is not stable. So @gfx added 2 hacks.
https://github.com/DroidKaigi/conference-app-2017/pull/194
https://github.com/DroidKaigi/conference-app-2017/pull/195

They were already merged.
Can you merge master and push again?

**Comment by lvla** [comment]
OK! I'll do it later!

**Comment by lvla** [comment]
DONE :D

**Comment by konifar** [comment]
Thank you so much! 💯

**Pull request merged**
