### PR TITLE
Add DroidKaigiClientTest

### PR DESCRIPTION
**Pull request by lvla**
## Issue
- none

## Overview (Required)
- extract DroidKaigiService and GithubService, and add these provider methods
- inject DroidKaigiService and GithuService to DroidKaigiClient
- add DroidKaigiClientTest

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Looks good! But sorry, can you merge master? 🙇

**Comment by lvla** [comment]
i'm resolving conflicts :D

**Comment by lvla** [comment]
failed😢
this might be caused by low memory

**Comment by chibatching** [comment]
I encountered same problem (ref: https://github.com/DroidKaigi/conference-app-2017/pull/157#issuecomment-277960490).
And I resolved it by adding option to disable gradle parallelism. 547ec87

**Comment by konifar** [comment]
@lvla CI succeeded! But conflict occurred. Can you merge again? 🙇

**Comment by konifar** [comment]
Thanks for contribution! LGTM!

**Comment by lvla** [comment]
thanks!

**Pull request merged**
