### PR TITLE
Fix my sessions clear when sessions update.

### PR DESCRIPTION
**Pull request by yatatsu**
## Issue
- #282

## Overview (Required)
- Update to [Orma 4.2.0-rc](https://github.com/gfx/Android-Orma), Replace deletion and insertion to `Relation#upsert()`.
- `Session` has nullable associations (`topic`, `speaker`, `room`), It seems to be difficult to replace. So try insert once, and update if fail.

## Links
- https://speakerdeck.com/lvla/ormahamaripointo-star-v2-dot-5-2 (japanese)

## Screenshot
- None

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
> Relation#upsert()

Interesting 🆒

**Comment by konifar** [comment]
@gfx Can you help to review? 🙇

**Comment by gfx** [comment]
Great PR 👍 

However `#upsert()` should work but it's not complete. Can you wait for the next RC?

**Comment by konifar** [comment]
@gfx Thank you for review! Okay, we can wait to merge.
Do you have a plan to release next RC? If you can release next week, I'll keep this PR. But if you can't, I'll close this once.

**Comment by gfx** [comment]
Upsert now works! https://github.com/yatatsu/conference-app-2017/pull/1

**Comment by konifar** [comment]
After merge https://github.com/yatatsu/conference-app-2017/pull/1 , I'll review and merge this 👍

**Comment by yatatsu** [comment]
I merged [yatatsu#1](https://github.com/yatatsu/conference-app-2017/pull/1), which is cool feature from Orma v4.2.0. Please review it!

**Comment by konifar** [comment]
LGTM! 💯 Thanks @yatatsu @gfx 
I'll merge this after CI Success

**Comment by gfx** [comment]
👏

**Pull request merged**
