### PR TITLE
Using the 'for' statement instead of create new Stream instance.

### PR DESCRIPTION
**Pull request by kitwtnb**
## Issue
- https://github.com/DroidKaigi/conference-app-2017/issues/365

## Overview (Required)
- Create new Stream instance every time 'onDraw' is called.
- So using 'for' statement.

## Links
- none

### CODE REVIEW

**Comment by konifar** [comment]
Thanks!! LGTM 💯

**Comment by eneim** [comment]
@konifar As reference for [this blog post](https://publicobject.com/2016/12/19/seductive-code/), I suspect that this fix gives same result: a new instance of Iterator is **implicitly** allocated for each *iterator for loop* call. My suggestion is to use the for loop using index (which simply get the instance from the list reference, no new thing is allocated). Your code looks like 1990 java but ...

P/S: sorry for being a bit OCD >.<. But 60fps FTW :p.

**Comment by konifar** [comment]
Sorry, Let me confirm your opinion 🤔 
You mean following code is better?

```java
for (int i = 0, size = particles.size(); i < size; i++) {
    particles.get(i).draw(canvas, paint);
}

List<Line> lines = createLines(particles);
for (int i = 0, size = lines.size(); i < size; i++) {
    lines.get(i).draw(canvas, paint);
}
```

**Comment by eneim** [comment]
@konifar Yes. The point is to prevent object allocation in onDraw, and Iterator by ```for (Object item: items)``` will implicitly create one (this is compiler work, we can do nothing). 

The second part is to produce new lines for the particle lis, but I think is fine now, so just reduce the allocation as much as possible :D.

**Pull request merged**
