### PR TITLE
Remove person icon in after party cell

### PR DESCRIPTION
**Pull request by kgmyshin**
## Issue
- #415

## Overview (Required)
- remove person icon in after party cell

## Links
-

## Screenshot
Before | After
:--: | :--:
 | 
 |

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by kgmyshin** [comment]
@konifar Should i remove lang-badge and feedback button in detail-fragment ? 🎅

**Comment by konifar** [comment]
Perfect! 💯 Thanks for quick fix! 😃

**Comment by jmatsu** [comment]
Thaaanks! LGTM!

**Comment by konifar** [comment]
> Should i remove lang-badge and feedback button in detail-fragment ?

Good point! Yes, I think so. Can you fix it on this PR? Or will you fix as another issue?

**Comment by kgmyshin** [comment]
> Can you fix it on this PR? Or will you fix as another issue?

I just do it in this PR. 🎅  👍

**Comment by konifar** [comment]
Cool :cool: Thanks!

**Comment by kgmyshin** [comment]
@konifar hi, just finished 🎅 

## Screenshot
Before | After
:--: | :--:
 |

**Comment by konifar** [comment]
Looks good! Thanks!
As for detail layouts, I think this mergin size should be 16dp.

remove_person_icon_in_after_party_cell_by_kgmyshin_ _pull_request__420_ _droidkaigi_conference-app-2017

But this is not necessary on this PullRequest! 😉

**Pull request merged**
