### PR TITLE
Change launch activity on notification tap

### PR DESCRIPTION
**Pull request by k-kagurazaka**
## Issue
- #151 

## Overview (Required)
- Change the launch activity on notification tap from `MainActivity` to `SessionDetailActivity`.
- `SessionDetailActivity` always navigates to `MainActivity` when "up button" is clicked.

## Links
- [Providing Up Navigation | Android Developers](https://developer.android.com/training/implementing-navigation/ancestral.html)

## Note
By the above Android Developers guideline, we should use `NavUtils#shouldUpRecreateTask` to check if `MainActivity` has been added to backstack, however the method always returns false as far as I worked.
So I now use custom action of `Intent` to check it.
Please tell me a good way for handling "up button" click event if you know.

Thanks.

### CODE REVIEW

**Comment by kobakei** [comment]
@k-kagurazaka 
Hi
Recently I have investigated how to implement UP button for such case so I put the link.
http://qiita.com/kobakei/items/ae1a6d2062f34d3f6771

The key point is adding SINGLE_TOP flag.

```java
upIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP);
```

**Comment by k-kagurazaka** [comment]
@kobakei 
Thanks for your information 😄 
I'll try it.

**Comment by k-kagurazaka** [comment]
I changed implementation from custom `Intent` action to `FLAG_ACTIVITY_SINGLE_TOP`.
I confirmed:

- When transitioned from `MainActivity`, back to `MainActivity` without recreation.
- When transitioned from the notification, move to `MainActivity` newly created.

**Comment by konifar** [comment]
LGTM! Thanks for contribution! 💯

**Pull request merged**
